name: pr-name-linter
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

env:
  NODE_VERSION: 14.8.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Dependencies
      run: npm install @commitlint/config-conventional
    - uses: JulienKode/pull-request-name-linter-action@v0.1.2